name: build and run tests
# https://github.com/avsm/setup-ocaml

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        # We don't want a full matrix because it is too slow, so we only have linear axes overriding these below.
        include:
          # Common configuration
          - os: ubuntu-24.04
            ocaml-compiler: 4.14.x

          # OCaml versions
          - os: ubuntu-24.04
            ocaml-compiler: 5.4.x
          - os: ubuntu-24.04
            ocaml-compiler: 5.3.x
          - os: ubuntu-24.04
            ocaml-compiler: 5.2.x
          - os: ubuntu-24.04
            ocaml-compiler: 5.1.x
          - os: ubuntu-24.04
            ocaml-compiler: 5.0.x
          - os: ubuntu-24.04
            ocaml-compiler: 4.13.x
          - os: ubuntu-24.04
            ocaml-compiler: 4.12.x

          # OS-s
          - os: ubuntu-22.04
            ocaml-compiler: 4.14.x
          - os: macos-26
            ocaml-compiler: 4.14.x
          - os: macos-15-intel
            ocaml-compiler: 4.14.x
          - os: macos-15
            ocaml-compiler: 4.14.x
          - os: macos-14
            ocaml-compiler: 4.14.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam pin add goblint-cil.dev . --no-action
      - run: opam depext goblint-cil --yes
      - run: opam depext goblint-cil --yes --with-test
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.ocaml-compiler }}
          path: _build/default/test/cil.log
